[pytest]
# --html: Sets the destination path for the report
# --self-contained-html: Merges CSS/Images into one file (highly recommended)
# --browser: Default browser for Playwright
addopts =
    --html=reports/automation_report.html
    --self-contained-html
    --browser chromium
    --headed
    -n auto
;    --reruns 2
;    --reruns-delay 2

# Tells pytest where your test files are located
testpaths = tests

# Allows your tests to import code from the 'src' folder easily
pythonpath = src

# Optional: Stop execution after X failures
# addopts = --maxfail=2
